module "access_management" {
  source                           = "../../modules/access-management"
  admin_observability_ag_name      = "${var.prefix}-${var.admin_observability_ag_name}"
  admin_network_ag_name            = "${var.prefix}-${var.admin_network_ag_name}"
  admin_security_ag_name           = "${var.prefix}-${var.admin_security_ag_name}"
  admin_compute_ag_name            = "${var.prefix}-${var.admin_compute_ag_name}"
  privileged_observability_ag_name = "${var.prefix}-${var.privileged_observability_ag_name}"
  privileged_network_ag_name       = "${var.prefix}-${var.privileged_network_ag_name}"
  privileged_security_ag_name      = "${var.prefix}-${var.privileged_security_ag_name}"
  privileged_compute_ag_name       = "${var.prefix}-${var.privileged_compute_ag_name}"
  observer_observability_ag_name   = "${var.prefix}-${var.observer_observability_ag_name}"
  observer_network_ag_name         = "${var.prefix}-${var.observer_network_ag_name}"
  observer_security_ag_name        = "${var.prefix}-${var.observer_security_ag_name}"
  observer_compute_ag_name         = "${var.prefix}-${var.observer_compute_ag_name}"
}
